apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    app: ticketruster
spec:
  containers:
    - name: web
      image: ticketruster
      imagePullPolicy: Never
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP